<h1><center> <b>LAB- 1(B)</b></h1>

## Aim: To perform Max-Min composition and Max-Product on given two fuzzy sets

## Theory:
Max-Min Composition: For two fuzzy relations R and S, the Max-Min composition is calculated by taking the maximum of the minimum values from each corresponding pair:

(R ∘ S)ij = max_k min(Rik, Skj)


Max-Product Composition: This operation calculates the maximum of the product of the corresponding elements from the relations R and S:

(R ⋅ S)ij = max_k (Rik ⋅ Skj)

In [ ]:
import numpy as np

class Relation:
    def __init__(self):
        self.row = int(input("Enter the no. of rows: "))
        self.col = int(input("Enter the no. of columns: "))
        self.relation = np.empty((self.row, self.col))

        print("Enter the elements: ")
        for i in range(self.row):
            self.temp = input("Enter the row(Space Seperated): ").split(' ')
            self.relation[i] = [float(j) for j in self.temp]
        print()

    def __repr__(self):
        print("Printing the elements: ")
        for row in self.relation:
            for element in row:
                print(element, end=" ")
            print()
        return ""

    def is_compatible(self, R):
        return self.relation.shape[1] == R.relation.shape[0]

    def min_max(self, R):
        if not self.is_compatible(R):
            print("Operation is not compatible")
            return None

        result = np.zeros((self.row, R.col))
        for i in range(self.row):
            for j in range(R.col):
                max_val = 0
                for k in range(self.col):
                    max_val = max(max_val, min(self.relation[i][k], R.relation[k][j]))
                result[i][j] = max_val
        return result
    def max_product(self, R):
        if not self.is_compatible(R):
            print("Operation is not compatible")
            return None

        result = np.zeros((self.row, R.col))
        for i in range(self.row):
            for j in range(R.col):
                val = 0
                for k in range(self.col):
                    val = max(val,self.relation[i][k]* R.relation[k][j])
                result[i][j] = val
        return result

In [ ]:
print("For relation R: ")
R=Relation()
print("For relation S: ")
S=Relation()
print(R)
print(S)
print("MIN_MAX product is: ")
print(R.min_max(S))
print("MAX product is: ")
print(R.max_product(S))

For relation R: 
Enter the no. of rows: 2
Enter the no. of columns: 2
Enter the elements: 
Enter the row(Space Seperated): 0.6 0.3
Enter the row(Space Seperated): 0.2 0.9

For relation S: 
Enter the no. of rows: 2
Enter the no. of columns: 3
Enter the elements: 
Enter the row(Space Seperated): 1 0.5 0.3
Enter the row(Space Seperated): 0.8 0.4 0.7

Printing the elements: 
0.6 0.3 
0.2 0.9 

Printing the elements: 
1.0 0.5 0.3 
0.8 0.4 0.7 

MIN_MAX product is: 
[[0.6 0.5 0.3]
 [0.8 0.4 0.7]]
MAX product is: 
[[0.6  0.3  0.21]
 [0.72 0.36 0.63]]
