<h1><center>Experiment: 8</center></h1>

# Aim:
To implement and demonstrate various genetic algorithm operators, including crossover and mutation techniques.

# Theory :
1. Crossover Operations:
Single-point crossover: This operation splits two parent arrays at a single crossover point and swaps the segments to produce offspring.
Multi-point crossover: It applies multiple crossover points, repeating the single-point crossover process at different positions.
Uniform crossover: It uses a probability array to decide which genes to swap between the parents at each position.
2. Mutation Operations:
Scramble mutation: A random subset of genes is selected, and their order is scrambled.
Inversion mutation: A subset of genes is selected, and their order is reversed, maintaining all the genes but in a different sequence.

## CrossOver


In [ ]:
import numpy as np

def single_point_crossover(A, B, x):
    A_new = np.append(A[:x], B[x:])
    B_new = np.append(B[:x], A[x:])
    return A_new, B_new

A = np.array([4, 8, 6, 5, 9, 2, 6, 9, 2, 3])
B = np.array([9, 8, 7, 4, 5, 2, 3, 5, 8, 7])
x = 2
single_point_crossover(A, B, x)

(array([4, 8, 7, 4, 5, 2, 3, 5, 8, 7]), array([9, 8, 6, 5, 9, 2, 6, 9, 2, 3]))

In [ ]:
import numpy as np

def multi_point_crossover(A, B, x):
    for i in x:
      A_new, B_new=single_point_crossover(A,B,i)
    return A_new, B_new

A = np.array([4, 8, 6, 5, 9, 2, 6, 9, 2, 3])
B = np.array([9, 8, 7, 4, 5, 2, 3, 5, 8, 7])
x = 2
single_point_crossover(A, B, x)

(array([4, 8, 7, 4, 5, 2, 3, 5, 8, 7]), array([9, 8, 6, 5, 9, 2, 6, 9, 2, 3]))

In [ ]:
import numpy as np

def uniform_crossover(A, B, P):
    for i in range(len(P)):
        if P[i] < 0.5:
            temp = A[i]
            A[i] = B[i]
            B[i] = temp
    return A, B

A = np.array([4, 8, 6, 5, 9, 2, 6, 9, 2, 3])
B = np.array([9, 8, 7, 4, 5, 2, 3, 5, 8, 7])
P = np.random.rand(10)
uniform_crossover(A, B, P)

(array([9, 8, 6, 4, 5, 2, 6, 5, 2, 7]), array([4, 8, 7, 5, 9, 2, 3, 9, 8, 3]))

##Mutation

1. Bit Flip Mutation

In this mutation, we flip the values of selected genes (change 1 to 0 and vice versa).

In [ ]:
import random

def bit_flip_mutation(chromosome, mutation_rate=0.1):
    for i in range(len(chromosome)):
        if random.random() < mutation_rate:  # Mutation probability
            chromosome[i] = 1 - chromosome[i]  # Flip the bit (1 becomes 0, 0 becomes 1)
    return chromosome

# Example usage
chromosome = [0, 1, 1, 0, 1, 0, 0, 1]
print("Before Bit Flip Mutation:", chromosome)
print("After Bit Flip Mutation:", bit_flip_mutation(chromosome.copy()))

Before Bit Flip Mutation: [0, 1, 1, 0, 1, 0, 0, 1]
After Bit Flip Mutation: [0, 1, 0, 0, 1, 1, 0, 1]


2. Random Resetting Mutation

In this mutation, we replace the value of selected genes with random values from their respective ranges.

In [ ]:
def random_resetting_mutation(chromosome, value_range, mutation_rate=0.1):
    for i in range(len(chromosome)):
        if random.random() < mutation_rate:
            chromosome[i] = random.choice(value_range)  # Randomly reset to a value in the given range
    return chromosome

# Example usage
chromosome = [2, 4, 3, 6, 1, 5, 3]
value_range = [1, 2, 3, 4, 5, 6]
print("Before Random Resetting Mutation:", chromosome)
print("After Random Resetting Mutation:", random_resetting_mutation(chromosome.copy(), value_range))

Before Random Resetting Mutation: [2, 4, 3, 6, 1, 5, 3]
After Random Resetting Mutation: [6, 4, 3, 6, 1, 5, 5]


3. Swap Mutation

In this mutation, two genes are randomly selected and their values are swapped.

In [ ]:
def swap_mutation(chromosome):
    i, j = random.sample(range(len(chromosome)), 2)  # Randomly select two different indices
    chromosome[i], chromosome[j] = chromosome[j], chromosome[i]  # Swap their values
    return chromosome

# Example usage
chromosome = [2, 4, 3, 6, 1, 5]
print("Before Swap Mutation:", chromosome)
print("After Swap Mutation:", swap_mutation(chromosome.copy()))

Before Swap Mutation: [2, 4, 3, 6, 1, 5]
After Swap Mutation: [2, 4, 6, 3, 1, 5]


4. Scramble Mutation

In this mutation, a subset of genes is randomly scrambled.

In [ ]:
def scramble_mutation(chromosome):
    start = random.randint(0, len(chromosome) - 1)
    end = random.randint(start, len(chromosome))
    subset = chromosome[start:end]
    random.shuffle(subset)
    chromosome[start:end] = subset  # Replace with scrambled version
    return chromosome

# Example usage
chromosome = [2, 4, 3, 6, 1, 5, 7]
print("Before Scramble Mutation:", chromosome)
print("After Scramble Mutation:", scramble_mutation(chromosome.copy()))

Before Scramble Mutation: [2, 4, 3, 6, 1, 5, 7]
After Scramble Mutation: [2, 4, 3, 6, 1, 5, 7]


5. Inversion Mutation

In this mutation, a subset of genes is selected and their order is reversed.

In [ ]:
def inversion_mutation(chromosome):
    start = random.randint(0, len(chromosome) - 1)
    end = random.randint(start, len(chromosome))
    chromosome[start:end] = chromosome[start:end][::-1]  # Reverse the subset
    return chromosome

# Example usage
chromosome = [2, 4, 3, 6, 1, 5, 7]
print("Before Inversion Mutation:", chromosome)
print("After Inversion Mutation:", inversion_mutation(chromosome.copy()))

Before Inversion Mutation: [2, 4, 3, 6, 1, 5, 7]
After Inversion Mutation: [2, 4, 3, 6, 1, 5, 7]
