<h1><center>Experiment: 9</center></h1>

# Aim:
Implement a Genetic Algorithm to optimize a solution by evolving a population through selection, crossover, and mutation over multiple generations.

# Theory:
The experiment involves implementing a Genetic Algorithm (GA) for solving optimization problems. GA mimics natural evolution processes, using concepts like chromosomes (solutions), genes (solution components), and populations (sets of chromosomes). The process involves:

Initialization: Generate an initial population of potential solutions.
Fitness Evaluation: Measure how good each solution is using a fitness function.
Selection: Choose the best solutions based on fitness for reproduction.
Crossover: Combine genes from two parent solutions to produce new offspring using single-point crossover.
Mutation: Introduce random changes to maintain diversity.
Termination: Repeat the process until a stopping criterion is met, such as achieving an optimal solution or reaching a set number of generations.
This method is effective for solving complex problems by evolving solutions over generations.

In [1]:
import numpy as np
def single_point_crossover(A, B, x):
    # Perform single-point crossover at point x
    A_new = np.append(A[:x], B[x:])
    B_new = np.append(B[:x], A[x:])
    return A_new, B_new

import random

def swap_mutation(chromosome):
    i, j = random.sample(range(len(chromosome)), 2)  # Randomly select two different indices
    chromosome[i], chromosome[j] = chromosome[j], chromosome[i]  # Swap their values
    return chromosome

In [2]:
def objective_function(chromosome):
    # Calculate the objective function
    return abs((chromosome[0] + 2 * chromosome[1] + 3 * chromosome[2] + 4 * chromosome[3]) - 30)

def calculate_fitness(population):
    # Calculate fitness based on the objective function
    return np.array([1 / (1 + objective_function(chromosome)) for chromosome in population])

def roulette_wheel_selection(population, fitness):
    # Calculate cumulative probabilities
    total_fitness = np.sum(fitness)
    probabilities = fitness / total_fitness
    cumulative_probabilities = np.cumsum(probabilities)

    # Perform roulette wheel selection
    selected_population = []
    for _ in range(len(population)):
        r = np.random.rand()  # Random value between 0 and 1
        for i, cumulative_probability in enumerate(cumulative_probabilities):
            if r <= cumulative_probability:
                selected_population.append(population[i])
                break

    return np.array(selected_population)

def single_point_crossover(A, B, x):
    # Perform single-point crossover at point x
    A_new = np.append(A[:x], B[x:])
    B_new = np.append(B[:x], A[x:])
    return A_new, B_new

# Input population
population_size = 6
chromosome_length = 4
population = []
print(f"Enter {population_size} chromosomes, each with {chromosome_length} genes (0-30):")
for i in range(population_size):
    while True:
        genes = list(map(int, input(f"Chromosome {i + 1} (4 genes): ").split()))
        if len(genes) == chromosome_length and all(0 <= g <= 30 for g in genes):
            population.append(genes)
            break
        else:
            print("Please enter exactly 4 genes, each between 0 and 30.")

population = np.array(population)

# Calculate fitness for each individual
fitness = calculate_fitness(population)

# Perform selection using roulette wheel
selected_population = roulette_wheel_selection(population, fitness)

# Perform single-point crossover on selected population (pairwise crossover)
crossover_population = []
for i in range(0, len(selected_population), 2):
    if i+1 < len(selected_population):
        parent1 = selected_population[i]
        parent2 = selected_population[i+1]
        # Choose a random crossover point (between 1 and chromosome_length - 1)
        crossover_point = np.random.randint(1, chromosome_length)
        child1, child2 = single_point_crossover(parent1, parent2, crossover_point)
        crossover_population.append(child1)
        crossover_population.append(child2)
    else:
        crossover_population.append(selected_population[i])  # In case of an odd number, keep the last individual

crossover_population = np.array(crossover_population)

# Perform mutation on the crossover population
Mutated_population = []
for i in range(0, len(crossover_population)):
    Mutated_population.append(swap_mutation(crossover_population[i]))

Mutated_population = np.array(Mutated_population)

# Display results
print("\nOriginal Population:\n", population)
print("Fitness Values:\n", fitness)
print("Selected Population:\n", selected_population)
print("Crossover Population:\n", crossover_population)
print("Mutated Population:\n", Mutated_population)

Enter 6 chromosomes, each with 4 genes (0-30):
Chromosome 1 (4 genes): 12 5 23 8
Chromosome 2 (4 genes): 2 21 18 3
Chromosome 3 (4 genes): 10 4 13 14
Chromosome 4 (4 genes): 20 1 10 6
Chromosome 5 (4 genes): 1 4 13 19
Chromosome 6 (4 genes): 20 5 17 1

Original Population:
 [[12  5 23  8]
 [ 2 21 18  3]
 [10  4 13 14]
 [20  1 10  6]
 [ 1  4 13 19]
 [20  5 17  1]]
Fitness Values:
 [0.0106383  0.01234568 0.01190476 0.0212766  0.01052632 0.01785714]
Selected Population:
 [[12  5 23  8]
 [ 2 21 18  3]
 [ 2 21 18  3]
 [ 1  4 13 19]
 [20  5 17  1]
 [ 2 21 18  3]]
Crossover Population:
 [[ 3 21 18 12]
 [ 2 23  5  8]
 [ 2 19 18 21]
 [ 1 13  4  3]
 [20 21  3 18]
 [ 2  5  1 17]]
Mutated Population:
 [[ 3 21 18 12]
 [ 2 23  5  8]
 [ 2 19 18 21]
 [ 1 13  4  3]
 [20 21  3 18]
 [ 2  5  1 17]]
